### ISSUE TITLE
Confirmation email functionality.

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#1]
Send users confirmation emails when they sign up for the site and register for the event.
## User Stories

As an end user
I want to receive a confirmation when I sign up for the site
so that I can remember my registration details later

As an event registrant
I want to receive a confirmation email when my event registration is submitted
so that I can later access my registration details

**Comment by brylie** [comment]
We may need to use a third party service, such as Mailgun, to deliver email.

**Comment by brylie** [comment]
> I set up a log in and then registered myself and "Oscar". I have not yet gotten any confirmation email. --Sarah Tyrrell (@styrrell)

**Comment by brylie** [comment]
This feature added thanks to @nizyev :-)

**Comment by styrrell** [comment]
Sorry, I think this is not working because registrations are not submitting #21 which is marked fixed but apparently not deployed yet.
I will look for confirmation email again once I can successfully submit a registration.

**Comment by brylie** [comment]
The confirmation email also needs  [SMTP server configuration](https://github.com/quaker-io/pym-2015/blob/master/server/smtp%20.js.example) to work, so please only re-open this issue if you verify that it does not work after configuration and other issues have been marked as resolved.
