### ISSUE TITLE
Add 'YAF Dorm' and 'YAF Camping' to the accommodations options

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#10]
Add options for 'YAF Dorm' and 'YAF Camping' to the accommodations options. This matches the options listed in the RepCom registration price schedule.
## User Stories

As a YAF,
I would like to see 'Dorm' and 'Camping' options for my peer group
so I can make sure I am going to be with my peer group

As a Registrar
I would like to provide the options 'YAF Dorm' and 'YAF Camping'
so that people in the YAF peer group can choose the option they need

**Comment by brylie** [comment]
Is there a price difference and/or accommodations limit for the YAF Dorm and Camping options? I am just wondering if this user story can be met with the existing functionality, specifically selecting the Young Adult Friends accommodations option.

**Comment by styrrell** [comment]
There is no price difference. The YAFs actually do not want to differentiate at registration time between YAF Dorm and Camping. They can just register for YAF Space, unless they want some other option (e.g., semi-private or family dorm space).

**Comment by brylie** [comment]
OK, lets leave the form as it is then?

**Comment by brylie** [comment]
I am closing this issue, as the young adult prices can be set to the same amount for camping and YAF space. The additional labels "YAF Camping" and "YAF Dorm" were determined to be unnecessary on the registration form.
