### ISSUE TITLE
Collect registrant postal address details

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#11]
Add field(s) to registration form to collect registrant address.
## User Stories

As a Registrar
I need registrant address details
so that we can sort geographically to link car pools, etc.

**Comment by brylie** [comment]
How should we collect the address information? E.g. one 'Address' field, or separate fields for 'street address', 'city', 'state', etc.? 

How will this information be used?

**Comment by joemagruder** [comment]
Because we would like to be able to sort geographically to link car pools, etc. we probably should do separate fields - street address, city, state, zip, country (primarily to cover Mexico).

**Comment by brylie** [comment]
@joemagruder alrignt. I am considering simple text fields for each, where the user must type each.

I have thought about a more complicated option where the state and country are select boxes, and the state values change dynamically when the country is changed. This seems difficult, and there is no ready-made solution that I could find.

**Comment by brylie** [comment]
I did another quick search and turned up a solution that would simplify this to a [single input field](http://lukemadera-packages.meteor.com/af-googleplace-basic), using [Google Places Autocomplete](https://atmospherejs.com/lukemadera/autoform-googleplace). However, this requires a Google service, which dynamically searches for known street addresses while the user types. As far as I understand, Google would not receive any data other than that submitted in the address field.

**Comment by brylie** [comment]
I also posted about this issue on the [Meteor community forum](https://forums.meteor.com/t/postal-address-fields/2160/1) to see if anyone has additional insight.
