### ISSUE TITLE
Collect registrant phone number

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#12]
Add a field to collect registrant phone number. Consider how the number might be consistently formatted.
## User Story

As a Registrar
I would like to collect registrant phone numbers
so that ... ?

**Comment by brylie** [comment]
What is the purpose of collecting phone numbers? Is this a manditory field? How do we handle youth, or other people that might not have a number or wish to share?

**Comment by joemagruder** [comment]
This should be optional. The phone number is used to communicate with the registrant about his/her registration and for the attenders list.

**Comment by brylie** [comment]
Alright, I will create a simple text field. I do not know of a simple way to normalize the phone number input, so that all numbers are consistent. This might need to be done as a post-process.
