### ISSUE TITLE
Collect registrant email address

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#14]
Add a field to collect an email address for each event registration. Consider whether the sign-in email address is sufficient for this purpose, or whether a unique email is expected for each registrant. Consider edge cases such as children or registrants who do not want to share their email address.
## User Story

As a Registrar
I would like to collect an email address responsible for each event registration
so that I can contact the responsible party

**Comment by brylie** [comment]
To clarify the current system: there are two types of registration on the online registration site
- the website registration
- the event registration

The **website registration** requires an email address, and can be used to link multiple event registrations into a single 'invoice'. Is the website registration email sufficient for the purposes of the registrars tracking/communication? What are the compelling reasons for requiring an individual email address for each event registrant?

**Comment by joemagruder** [comment]
The compelling reasons for individual email addresses are two: We may need to communicate with individual registrants about their registration and we will be asked to create an attenders list that gives the email address for each individual. Note that this field should be an optional, not mandatory field.

**Comment by brylie** [comment]
> email address for an individual registration is not being requested. --Sarah Tyrrell @styrrell

**Comment by brylie** [comment]
This is now included on the form as an optional field.
