### ISSUE TITLE
Reduced day rate for Monday and Saturday (half days)

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#18]
When calculating the prices for daily registrants, Monday and Saturday should be reduced by half, as they are half days.

**Comment by styrrell** [comment]
The reduction should be $10, not by half.

**Comment by styrrell** [comment]
First-time attenders get a $40 discount. Need a check box to indicate first-timer and the associated fee reduction logic.

**Comment by brylie** [comment]
Please file a new issue for the first time attender feature.

On 31 March 2015 12:01:17 EEST, SarahTyrrell <notifications@github.com> wrote:
>First-time attenders get a $40 discount. Need a check box to indicate
>first-timer and the associated fee reduction logic.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/quaker-io/pym-2015/issues/18#issuecomment-88002672

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
