### ISSUE TITLE
Incorporate $40 discount for first-timers

### ISSUE THREAD

**Issue by styrrell** [quaker-io/pym-2015#19]
First-time attenders get a $40 discount. Need a check box to indicate first-timer and the associated fee reduction logic. I am guessing the added logic means this needs to be a separate issue, instead of part of fee adjustment.

**Comment by brylie** [comment]
Yup. Thanks @styrrell. I'll add the additional logic to the fee calculation.

**Comment by brylie** [comment]
@quaker-io/pym-2015 please test the 'First time attender discount' functionality. 

Specifically, there is now a checkbox on the registration form that, when toggled, should dynamically adjust the calculated value on the 'Register' button. Additionally, the discounted value should be saved to the database and visible on the Registrar Dashboard.

**Comment by brylie** [comment]
This seems to be working, but still needs testing. Closing issue.
