### ISSUE TITLE
View family/group registrations

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#2]
Add capability for a primary registrant to view all sub-registrants, e.g. family members, associated with the primary account.
## User Stories

As a family primary event registrant,
I would like to see the registration details for related registrations
So that I can review and manage the details

As a registrant who has also registered other persons
I would like to view all related registrations in a single list
so that I can review and manage registration details

**Comment by brylie** [comment]
This functionality assumes a primary registrant, who is responsible for the additional registrants. I can create this capability through the website login/registration system, which is based on email address. This way, a primary PYM registrant would register an account on the online registration website where they can register one or more event participants.

**Comment by brylie** [comment]
Joe replied to the email thread:

> We need to figure out how to link families. Perhaps a check box for family vs. individual registration. Then I can figure the families out.

**Comment by brylie** [comment]
Using a shared 'primary contact email' address would help us to link group/family registrations. The website already requires an email address to sign-up, and this address can be attached to each event registration - allowing us to link them together.

**Comment by joemagruder** [comment]
The primary contact email address should work as a link. It is interesting how our perception of stable family identifiers has changed - from the name of the oldest male to street addresses to phone numbers to one person's (could be the oldest male, could be the youngest child...) email.

**Comment by brylie** [comment]
> I see no way in the site to review my family's registrations as a group. --Sarah Tyrrell @styrrell

**Comment by brylie** [comment]
This is now included in the platform. Registrations are grouped by primary account email.

**Comment by brylie** [comment]
This is a duplicate of issue #22
