### ISSUE TITLE
Add help text about communicating complicated schedule needs

### ISSUE THREAD

**Issue by styrrell** [quaker-io/pym-2015#20]
Anyone not staying the full week, except infants 0-5, should see the dinner check boxes, for Tuesday through Friday. (Monday we are saying dinner is included, since lunch is not provided).

The charge is $20 for adults and teens, $10 for children 5-12.

**Comment by brylie** [comment]
Based on the feature description, this seems non-trivial.
- branching logic
  - not staying full week
  - not 0-5
- variable pricing
  - adults and teens
  - children

Any solution would need testing and feedback.

I estimate that this feature would take at least two weeks to build and test.

**Comment by brylie** [comment]
What are some alternative ideas that would not involve additional logic in the software or checkboxes for the registrant? What is the user story here? E.g. what need are we trying to meet?

**Comment by joemagruder** [comment]
I suggest modifying the text  box instructions to include additional meals or saying something like if you have a more complex schedule, send an email to the registrars. I'm not clear about when a person staying overnight and past the next day's dinner needs to pay a day attender fee. I also don't recall this being an issue in the past.

**Comment by brylie** [comment]
>  if you have a more complex schedule, send an email to the registrars

Thanks for the clarification @joemagruder. The help text is a simple addition to the form.

**Comment by styrrell** [comment]
Ok -- so we are not going to have check-boxes -- is that right?
Brylie, this is still marked as help wanted. What do you need here -- suggestions for the help text?
And this will just be text to inform the registrant -- not something for them to fill in -- is that right?

**Comment by brylie** [comment]
Yeah, I will add the text to the form. I just want feedback on what text would be good. E.g.:

> if you have a more complex schedule, send an email to the registrars

**Comment by joemagruder** [comment]
That text looks adequate to me.

---------- Original Message ----------

**Comment by brylie** [comment]
Great! I'll add it today.

**Comment by brylie** [comment]
OK, I added the help text, as described above.
