### ISSUE TITLE
Create text for introductory page

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#25]
Create text to display on the front page of registration micro-site. The text should be brief (e.g. 500 words or less) and include a pricing table. Also include links to sign-up, so that users can proceed with registration.
## User Stories

As a registrant
I would like a brief introduction on to the registration site
so that I can know what to expect and how much registration costs

**Comment by styrrell** [comment]
@brylie Joyce and I are working on this, hope to have something to you soon. Would it be possible to get last year's text?

**Comment by brylie** [comment]
Yes. Sorry for the delay. I will find the text ASAP.

On 10 April 2015 11:28:04 EEST, SarahTyrrell notifications@github.com wrote:

> @brylie Joyce and I are working on this, hope to have something to you
> soon. Would it be possible to get last year's text?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quaker-io/pym-2015/issues/25#issuecomment-91477179

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brylie** [comment]
On searching the site, I was only able to find [text for the 2012 online registration form](http://www.pacificyearlymeeting.org/2012/documents/pym-on-line-registration-form/).

**Comment by styrrell** [comment]
We have this now as a Microsoft Word document. Git says I can attach images, but I am not sure about other types of documents, so I will send it to @brylie attached to a e-mail. The text has been reviewed by Sarah, Joyce, and Janet Gastil, but Joe and Margaret have not commented, So they may request some (hopefully minor) changes.

**Comment by brylie** [comment]
I have updated the introductory text with minor modifications to aid in visual scanning.

**Comment by brylie** [comment]
I will deploy the latest changes to the registration portal ASAP.
