### ISSUE TITLE
Add 'grade in school this year' field

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#27]
> It would be very useful for us to ask "Grade in School this year." --Alyssa Nelson
## User Stories

As a child or youth program teacher
I would like to know the grade in school for each of my students
so that I can select age appropriate activities and groupings

**Comment by brylie** [comment]
This might require conditional logic, so that it only shows for people below an age threshold.

**Comment by brylie** [comment]
What need would be met with this information? E.g. how would it be used? 

I would like to write a 'user story' for this request.

**Comment by styrrell** [comment]
It would be used by Children's Program and JYM both, I believe. It would guide them in setting up developmentally appropriate programs and groupings. Children of the same age can be at quite different levels developmentally, and being held back or moved ahead a grade is an indicator of developmental level.

**Comment by brylie** [comment]
For what age groups would this field be visible? What options would be allowed for the input?

On 5 April 2015 02:50:15 EEST, SarahTyrrell notifications@github.com wrote:

> It would be used by Children's Program and JYM both, I believe. It
> would guide them in setting up developmentally appropriate programs and
> groupings. Children of the same age can be at quite different levels
> developmentally, and being held back or moved ahead a grade is an
> indicator of developmental level.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quaker-io/pym-2015/issues/27#issuecomment-89690085

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joemagruder** [comment]
Most people have the sense to leave the field blank if it doesn't refer to them - e.g., if they haven't started school yet or if they are past high school. Of course, some don't- mostly folks proud of their years of education. That's not a problem. So, it should work as a non-mandatory field. We can always contact the parents of the 12-year old who left the field blank.

**Comment by styrrell** [comment]
Based on feedback (some very strong) from the Children's and Teen Program folks and Alyssa, I am removing the enhancement label and adding this to MVP. We really do need this. It is OK if the field shows for everyone. Make it a non-mandatory field as Joe suggests. I think valid inputs could be Preschool, Kindergarten, and 1 through 12 (pull down choice maybe?). I think just a text box would be fine too, if that is easier at this point. Thanks!

**Comment by styrrell** [comment]
OK, I thought maybe the enhancement label meant an optional feature, but I see other MVP issues with the label, so I am adding it back to this issue.

**Comment by brylie** [comment]
@kerwinf or @styrrell, would you consider contributing to complete this task? I can help to get you started.

**Comment by brylie** [comment]
Also, we can consider how to collect information like this in stages, so that the initial registration form is simple. E.g. we can create a report by age grouping that can be used for follow-up communications.

**Comment by joemagruder** [comment]
A 2 character non-mandatory text field is all we need.

**Comment by styrrell** [comment]
Yes, I would consider contributing to complete this, if you can help get me started. I have the repository cloned locally, have meteor installed, and can run locally and view the local site.

**Comment by brylie** [comment]
Grade in school now conditionally displays for child, youth, and teen age groups.
