### ISSUE TITLE
Determine correct age ranges for age grouping

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#37]
Make sure the age ranges in the online registration match the paper version.

**Comment by brylie** [comment]
> Age ranges: Infant is 0-5, child is 6-12, JYM/youth is 13-18. We have separate rates for teens staying with their families or sponsors rather than in JYM housing. --Sarah Tyrrell @styrrell

**Comment by brylie** [comment]
> The remaining question is what the age parameters for Young Adult Friends are. If it is 19 - 35, then are we saying that a 30 year old adult who stays in the dorm pays $295, but if she camps she pays $480? -- Joe Magruder

**Comment by brylie** [comment]
> I put youth as 13-17 and YAF as 18-35.  Reasoning is that an 18-year old is legally an adult. -- Margaret Mossman

**Comment by styrrell** [comment]
A 30 year old who camps or stays in the YAF dorm space, should pay at the YAF rates: $295 for the week, or $60 per day. The difference would be for semi-private: they would pay the adult rate for semi-private. I hope that helps clear things up?

(I think they also should pay the YAF rate if they want family dorm space -- but I think that is complicated to figure and does not seem to be reflected in the fee structure approved at RepCom. And there were no such requests last year (only 2 families asked for family dorm as I recall, and the parents were older than YAF age range))

**Comment by brylie** [comment]
We have a set rate for the YAF space for young adults, and adults. 

What are the age ranges for the age groups?

On 5 April 2015 02:41:45 EEST, SarahTyrrell notifications@github.com wrote:

> A 30 year old who camps or stays in the YAF dorm space, should pay at
> the YAF rates: $295 for the week, or $60 per day. The difference would
> be for semi-private: they would pay the adult rate for semi-private. I
> hope that helps clear things up?
> 
> (I think they also should pay the YAF rate if they want family dorm
> space -- but I think that is complicated to figure and does not seem to
> be reflected in the fee structure approved at RepCom. And there were no
> such requests last year (only 2 families asked for family dorm as I
> recall, and the parents were older than YAF age range))
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quaker-io/pym-2015/issues/37#issuecomment-89689125

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brylie** [comment]
@styrrell will you please help us with determine the pricing structure in issue #15?

**Comment by brylie** [comment]
Here are the current values, after reviewing the paper registration form:
- 0-5: child
- 6-12: youth
- 13-17: teen
- 18-25: yaf
- 26+: adult

**Comment by joemagruder** [comment]
I think the current values are reasonable.

**Comment by brylie** [comment]
@joemagruder thanks for verifying.
