### ISSUE TITLE
Determine whether first time attender discount preceeds early discount/late fee calculation

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#38]
The 5% early discount/late fee would be different depending on whether it was calculated before or after the first time registration discount were applied. Determine which order to perform these operations.

**Comment by brylie** [comment]
> The $40 first-time attender discount has a different effect if applied before or after the early/late percentage figures.  I personally think it should be after, i.e. be a flat figure. --Margaret Mossman

**Comment by joemagruder** [comment]
I think the early and late fee adjustment comes after the discount is figured.

**Comment by brylie** [comment]
Related issue: #36
