### ISSUE TITLE
Allow 'other' option for Meeting field

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#48]
Some registrants may come from meetings or Quaker organizations not in the Meetings list. Allow registrants to input names not in the current list.
## User stories

As a registrar
I need to know what meeting or Quaker organization people are affiliated with
so that I can print it on name badges

**Comment by brylie** [comment]
I am considering using an [auto-complete](https://github.com/mizzao/meteor-autocomplete) option, rather than a select box. This would let users input any value while suggesting common values for consistency.

**Comment by styrrell** [comment]
I think auto-complete would be fine -- or even just a text box.

 ;Sarah

**Comment by brylie** [comment]
OK, text box would be simple. I would also like for the input to be consistent (e.g. spelling, capitalization, wording, etc.), if possible.

**Comment by brylie** [comment]
I changed the 'registrant meeting' field to 'registrant affiliation' and set it to be a plain text box.

**Comment by brylie** [comment]
I am marking this as closed now, as the input allows any value.
