### ISSUE TITLE
Adjust event registration fees

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#5]
Adjust the event registration fees so they reflect the fee schedule and options determined at RepCom.
# FEE SCHEDULE FOR 2015 (PROPOSED)

The current fee schedule, with combinations allowed on the registration form, is defined in [prices.js](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L18-L108https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L18-L108)
## User Stories

As a registrar
I expect the event fees to match those determined at RepCom
so that users can begin registering online starting April 1st

As an event registrant
I would like the event fees to match those determined at RepCom
so that I know I am being charged a fair rate for online event registration

**Comment by brylie** [comment]
@kerwinf are you still working on this?

**Comment by kerwinf** [comment]
Yes, just haven't had a chance to finish it up.

I notice there are different prices for young friends. The new price schedule doesn't have that listed. Can I just remark them out?

Kerwin

**Comment by styrrell** [comment]
@brylie, @kerwinf -- Joyce and I are thinking of two tweaks to the fees:

1) A charge for extra dinners. The per-day rates include dinner only if you are staying that night. We would also need check-boxes for registrants to request dinner on Tuesday through Friday nights.

2) A slightly reduced day rate for Monday and Saturday (partial days).

Not sure yet whether Finance Committee is OK with these, but if they are, would these be hard to add?

**Comment by brylie** [comment]
> 2) A slightly reduced day rate for Monday and Saturday (partial days).

@styrrell I created another issue (#18) for the half day task, as it will take specific coding effort.

**Comment by brylie** [comment]
> The per-day rates include dinner only if you are staying that night. We would also need check-boxes for registrants to request dinner on Tuesday through Friday nights.

@styrrell  What type of registrants would see these check-boxes (e.g. Commuter)? When would they be visible in the form?

**Comment by brylie** [comment]
>  I notice there are different prices for young friends. The new price schedule doesn't have that listed. Can I just remark them out?

@kerwinf we need to make sure the named price _keys_ map to _values_ in the form inputs and database validation. 
- [prices.js](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L30-L48) lists `youngAdult.daily.yaf` and `youngAdult.weekly.yaf`, which may need to be changed and expanded to include `yafDorm` and `yafCamping`. 
- [registrants.js](https://github.com/quaker-io/pym-2015/blob/master/both/collections/registrants.js#L42-L51) `accommodations.allowedValues` then needs to have the decided values added
- Lastly, [accommodations.js](https://github.com/quaker-io/pym-2015/blob/master/client/templates/register/accommodations/accommodations.js#L60-L69) _values_ must also match (although label text can be anything sensible).

Briefly, the purposes of the three files are:
- prices.js - data structure containing event-specific price schedule
- registrants.js - database definition and data validation (event registrants collection)
- accommodations.js - template logic, in this case dynamically changing accommodation options based on age group

**Comment by styrrell** [comment]
Anyone not staying the full week, except infants 0-5, should see the dinner check boxes, for Tuesday through Friday. (Monday we are saying dinner is included, since lunch is not provided).

The charge is $20 for adults and teens, $10 for children 5-12.

**Comment by brylie** [comment]
Based on the above description, the checkboxes seem relatively complicated:

* branching logic
  * not staying full week
  * not 0-5
* variable pricing
  * adults and teens
  * children

Any solution would need testing and feedback.

I estimate that this feature would take at least two weeks to build and test.

**Comment by brylie** [comment]
@kerwinf we can leave the data structure as it is, and just swap in the correct prices. That way the _registrants.js_ and _accommodations.js_ don't need to be changed.

**Comment by brylie** [comment]
@styrrell will you please open an issue for the above mentioned food checkboxes?

**Comment by brylie** [comment]
@kerwinf are you still working on this task?

**Comment by brylie** [comment]
Just so we have all the relevant information in this thread, here is the price schedule from the [Finance Committee's RepCom report](http://www.pacificyearlymeeting.org/wordpress/wp-content/uploads/2015/02/FinCom-Report-RepCom-2015.pdf).

**Comment by brylie** [comment]
I revised the price structure to more closely resemble our data structure. There are a couple of open questions:
- What do we do about teens?
- What are the age ranges for these groups?
- What are the missing prices for the Young Adult Friends? 
  - Do we just use the Adult prices?

**Comment by kerwinf** [comment]
I have updated the prices from the RepCom Report. There are a few questions I have.
1. Youth Family Dorm is not specified in the prices.js file, should they be added as such?
2. YAF or JYM only has 2 prices and are not age specified. The prices.js file has them separated by age. How should this be handled?
3. Should I change the prices in the prices.js file to 0 if there is no matching item on the RepCom Report?

**Comment by brylie** [comment]
> Youth Family Dorm is not specified in the prices.js file, should they be added as such?

Would 'youth > daily > dorm' or 'youth > weekly > dorm' be equivalent?

> YAF or JYM only has 2 prices and are not age specified. The prices.js file has them separated by age. How should this be handled?
> Try to use the structure I added to the beginning of this issue thread.

YAF and JYM are _accommodations_ that both the Young Adult Friends and Teen _age groups_ can choose from.

> Should I change the prices in the prices.js file to 0 if there is no matching item on the RepCom Report?

If they are not relevant, we should _remove_ them from the prices.js as well as the age group [accommodation options](https://github.com/quaker-io/pym-2015/blob/master/client/templates/register/accommodations/accommodations.js#L22-L70).

## Data structure

As a general pattern, the data structure is organized as such:
- AgeGroup
  - Registration Type
    - Accommodations

## Relevant files
- [age_groups.js](https://github.com/quaker-io/pym-2015/blob/master/lib/age_groups.js) - calculates **age group** based on the age input
  - 0-5: child
  - 6-10: youth
  - 11-17: teen
  - 18-25: yaf
  - 26+: adult
- [accommodations.js](https://github.com/quaker-io/pym-2015/blob/master/client/templates/register/accommodations/accommodations.js#L22-L70) - uses the **age group** to display relevant accommodation options

**Comment by brylie** [comment]
@styrrell will you please help us sort out the prices and data structure?

**Comment by brylie** [comment]
@kerwinf also, we did have a discussion regarding the age group accommodation options, which led to the current data structure. So, it might be a matter of determining the missing values, rather than removing the accommodations options.

**Comment by styrrell** [comment]
Here are the rates with question marks, filled in.

Young Adult Friends

```
Commuter : 55
Daily
    Camping: 60
    Dorm: 60
    Semiprivate: 165
    YAF: 60
    JYM: NOT APPLICABLE -- JYM is under 18
Weekly
    Camping: 295
    Dorm: 295
    Semiprivate: 795
    YAF: 295
    JYM: NOT APPLICABLE -- JYM is under 18
```

Teens

```
Commuter : 55
Daily
    Camping: 60 (with Parent/Sponsor ONLY)
    Dorm: 75 (with Parent/Sponsor -- not JYM Dorm)
    Semiprivate: 75
    YAF: NOT APPLICABLE -- YAF is 18 or over
    JYM: 60
Weekly
    Camping: 300 (with Parent/Sponsor ONLY)
    Dorm: 300  (with Parent/Sponsor -- not JYM Dorm)
    Semiprivate: 345
    YAF: NOT APPLICABLE -- YAF is 18 or over
    JYM: 295
```

**Comment by brylie** [comment]
These changes have been added. Also, it was decided at one point to allow a grey area for early/late transition from JYM to YAF, which the current form allows as far as accommodations go.

On 6 April 2015 13:37:23 EEST, SarahTyrrell notifications@github.com wrote:

> Here are the rates with question marks, filled in.
> 
> Young Adult Friends
> 
>    Commuter : 55
>    Daily
>        Camping: 60
>        Dorm: 60
>        Semiprivate: 165
>        YAF: 60
>        JYM: NOT APPLICABLE -- JYM is under 18
>    Weekly
>        Camping: 295
>        Dorm: 295
>        Semiprivate: 795
>        YAF: 295
>        JYM: NOT APPLICABLE -- JYM is under 18
> 
> Teens
> 
>    Commuter : 55
>    Daily
>        Camping: 60 (with Parent/Sponsor ONLY)
>        Dorm: 75 (with Parent/Sponsor -- not JYM Dorm)
>        Semiprivate: 75
>        YAF: NOT APPLICABLE -- YAF is 18 or over
>        JYM: 60
>    Weekly
>        Camping: 300 (with Parent/Sponsor ONLY)
>        Dorm: 300  (with Parent/Sponsor -- not JYM Dorm)
>        Semiprivate: 345
>        YAF: NOT APPLICABLE -- YAF is 18 or over
>        JYM: 295
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/quaker-io/pym-2015/issues/5#issuecomment-90010238

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brylie** [comment]
Thanks for your help here @kerwinf!

**Comment by styrrell** [comment]
I am not seeing the correct fees being calculated (as shown on the Register button), at least in some cases. I tried the below, I see $192.85. The fee (including the 5% early discount) should be 280.25.
The email for my account is sarahtyrrell@alumnae.mills.edu.
I tried two test registrations: SarahTestApril12_01 Tyrrell and SarahTestApril12_02 Tyrrell.
Both 14 years old, full week, JYM housing.

**Comment by brylie** [comment]
Here is the procedure the form uses:
1) [Teen > weekly > JYM](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L73)  is **$203** 
2)  203 x [0.05](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L9) is **10.15**
3) 203 - 10.15 = **192.85**

Do the underlying calculations need to change? Do we have the [prices](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L17-L108) correct?

**Comment by styrrell** [comment]
The prices are not correct. Teen weekly in JYM dorm should be $295. I do not know where the $203 came from, I do not see that amount anywhere in the fee structure approved at RepCom.

The calculation looks correct to me, we just need to start with the correct prices.

Do you need help with this?

**Comment by brylie** [comment]
Yes, the task for this issue is to adjust the event registration fees, so that they are correct. Please review and update the registration fees in [lib/prices.js](https://github.com/quaker-io/pym-2015/blob/master/lib/prices.js#L17-L108). Note, all age group/accommodations combinations in that structure need _numeric_ values, as they are all used in some combination of calculation in our registration form.

**Comment by brylie** [comment]
Based on the recent commit activity, I will close this issue again.
