### ISSUE TITLE
Change field order in CSV export

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#58]
Determine a desirable field order in the CSV export, and re-order the fields to match.

**Comment by brylie** [comment]
I have worked on this issue a bit, and have implemented the following field order:
- "last_name"
- "first_name"
- "age"
- "ageGroup"
- "registrantEmail"
- "postalAddress"
- "telephone"
- "firstTimeAttender"
- "registrationType"
- "accommodations"
- "days"
- "linens"
- "foodPreference"
- "specialNeeds"
- "carbonTax"
- "fee"
- "createdAt"
- "_id"
- "createdByEmail"

**Comment by joemagruder** [comment]
Registrant Affiliation should be included.
Is there a visible registration date? This may be needed to settle disputes about early discounts, late fees, etc.  (I know that the "createdAt" is a date/time stamp, but can it be translated, e.g., into an Excel date using a formula of some sort?)

**Comment by brylie** [comment]
I added an issue to track the feature request [Add 'registrant affiliation' to CSV export](https://github.com/quaker-io/pym-2015/issues/59).

**Comment by brylie** [comment]
I created an issue to track the feature request [Format 'createdAt' date in CSV export](https://github.com/quaker-io/pym-2015/issues/60).

**Comment by brylie** [comment]
Closing issue, as there are no additional requests for field ordering.
