### ISSUE TITLE
Collect non-food special needs

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#6]
Create a field where users can enter non-food related special needs.
## User Stories

As an event registrant
I need to communicate my special needs to the Registrars
so that I can make sure I have appropriate accommodations

As a Registrar
I need to know about registrants' special needs
so that I can make sure to accommodate their needs

**Comment by brylie** [comment]
Would a general text field be alright here? E.g. 'enter details about any special needs you may have.' The text field would be similar to the 'Leave a comment' text area below.

**Comment by brylie** [comment]
Joe commented via an email thread:

> a text box for housing/mobility special needs

**Comment by joemagruder** [comment]
Yes, a general text field would be adequate.

**Comment by brylie** [comment]
> I do not see any place to enter non-food special needs (mobility issues, etc). --Sarah Tyrrell @styrrell

**Comment by brylie** [comment]
I added a text area for special needs.
